v0001:
  AGN:
    PATH: '../data/cats/veron_cetty_agn_radec_pm_cleaned.fits'
    RA_BEST: 'RA'
    DEC_BEST: 'DEC'
  HMXRB:
    PATH: '../data/cats/hmxrb_neumann_2023.fits'
    RA_BEST: 'RA_ICRS'
    DEC_BEST: 'DE_ICRS'
  LMXRB:
    PATH: '../data/cats/lmxrb_avakyan_2023.fits'
    RA_BEST: 'RA_ICRS'
    DEC_BEST: 'DE_ICRS'


